### ISSUE TITLE
Cookie for requested domain crashes Android App instantly

### ISSUE THREAD

**Issue by roeder82** [trigger-corp/trigger.io-request#3]
Currently we are using the request module to send native calls (e.g. upload camera image). We are using a code snipped like this:

```
window.forge.request.ajax({
  type: 'GET',
  url: 'http://example.org',
  timeout: 3600000
});
```

Setting a Cookie for the domain example.org crashes the Android app instantly with the following stack trace:

```
04-09 11:07:54.284 13271 13570 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-09 11:07:54.284 13271 13570 E AndroidRuntime: Process: rocks.staffbase.adfrtesting, PID: 13271
04-09 11:07:54.284 13271 13570 E AndroidRuntime: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.h.a.a(Unknown Source:44)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.h.a.a(Unknown Source:20)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.l.a(Unknown Source:274)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.l.a(Unknown Source:4)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.l.a(Unknown Source:20)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.e.a(Unknown Source:5)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.a.intercept(Unknown Source:185)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:161)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.j.intercept(Unknown Source:59)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:161)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:6)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.y.f(Unknown Source:115)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.y$a.c(Unknown Source:4)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at b.a.b.run(Unknown Source:17)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-09 11:07:54.284 13271 13570 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:764)
04-09 11:09:27.980 13615 13892 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-09 11:09:27.980 13615 13892 E AndroidRuntime: Process: rocks.staffbase.adfrtesting, PID: 13615
04-09 11:09:27.980 13615 13892 E AndroidRuntime: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.h.a.a(Unknown Source:44)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.h.a.a(Unknown Source:20)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.l.a(Unknown Source:274)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.l.a(Unknown Source:4)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.l.a(Unknown Source:20)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.e.a(Unknown Source:5)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.a.intercept(Unknown Source:185)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:161)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.j.intercept(Unknown Source:59)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:161)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.c.g.a(Unknown Source:6)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.y.f(Unknown Source:115)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.y$a.c(Unknown Source:4)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at b.a.b.run(Unknown Source:17)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-09 11:09:27.980 13615 13892 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:764)
```

Some googling around revealed a problem with the OkHTTP module: https://github.com/square/okhttp/issues/3582

So maybe an update of the OkHTTP module could help.

As this will soon become a blocker for us, we'd like to raise this as early as possible @antoinevg

**Comment by antoinevg** [comment]
Your sample code, as written, does not reproduce the problem.

I'm also not managing to reproduce the problem using something like:

    forge.request.ajax({
        type: "GET",
        url: "https://httpbin.org/cookies/set/plink/plonk",
        success: function (response) {
            forge.logging.log(JSON.stringify(response));
        }
    });

Can you please provide a code snippet that reproduces the problem.

**Comment by antoinevg** [comment]
For what it's worth, I've uploaded a version of the module which updates okhttp to the latest non-breaking release (3.11.0) and adds the new set of recommended proguard rules:

https://trigger.io/modules/request/v2.11/

Please give it a try, if that doesn't sort it out I'm still going to need some code from you I can use to reproduce the issue on my side :-)

**Comment by roeder82** [comment]
Great I try it.

**Comment by roeder82** [comment]
The new version seems to work for that case. Thanks a lot for the fast help.
